language: c
dist: xenial
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsdl2-2.0-0 libsdl2-dev libsdl2-image-2.0-0 libsdl2-image-dev

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - make
  - make test
